cosmos-installer:
  form:
    - name: configPath
      label: What is the path to your config? (required path)
      initialValue: "{DefaultDataPath}/NZBHydra/config"
      type: text
    - name: downloadPath
      label: What is the path to your downloads? (required path)
      initialValue: "{DefaultDataPath}/NZBHydra/downloads"
      type: text
services:
  "{ServiceName}":
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: "{ServiceName}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Auto
    volumes:
      - source: "{Context.configPath}"
        target: /config
        type: bind
      - source: "{Context.downloadPath}"
        target: /downloads
        type: bind
    restart: unless-stopped
    routes:
      - name: "{ServiceName}"
        description: Expose {ServiceName} to the web
        useHost: true
        target: http://{ServiceName}:5076
        mode: SERVAPP
        Timeout: 14400000
        ThrottlePerMinute: 12000
        BlockCommonBots: true
        SmartShield:
          Enabled: true
